#version 460
#pragma shader_stage(compute)

layout(local_size_x = 1024) in;

#include "../types.glsl"

layout(binding = 0, std430) restrict readonly buffer Temp {
	uint b_temp[];
};
layout(binding = 1, std430) restrict buffer Commands {
	Command b_commands[];
};

layout(push_constant) uniform Constants {
	uint u_commandCount;
};

void main() {
	
	uint gid = gl_GlobalInvocationID.x;
	if (gid >= u_commandCount)
		return;
	
	b_commands[gid].firstInstance += b_temp[gl_WorkGroupID.x];
	
}
