#version 460
#pragma shader_stage(compute)

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba16f) restrict writeonly uniform imageCube cubemap;
layout(binding = 1) uniform Sides {
	mat4 sides[6];
};

void main() {
	const uvec3 gid = gl_GlobalInvocationID;
	const ivec2 size = imageSize(cubemap);

	vec2 uv = vec2(gid.xy) / vec2(size);
	uv = uv * 2.0 - 1.0;
	vec3 dir = mat3(sides[gid.z]) * vec3(uv, 1.0);

	imageStore(cubemap, ivec3(gid), vec4(uv+vec2(1.0), 1.0, 1.0));
}
